# .github/workflows/ci.yml
name: CI for push on branch

on:
  push:
    branches:
      - '*'  # Trigger on any branch push
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      run_docs: true
